# Generated by Django 3.2.9 on 2021-11-17 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_auto_20211117_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='L3Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='l3',
            name='type',
            field=models.CharField(choices=[('BID', 'bids'), ('ASK', 'asks')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='l3',
            name='version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blockchain.l3version'),
            preserve_default=False,
        ),
    ]
