# Generated by Django 3.2.9 on 2021-11-17 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_auto_20211117_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='l3',
            old_name='type',
            new_name='order_type',
        ),
    ]
